---
abstract: 'basic SOCKS5 connection support for IO::Async'
author:
  - 'Tom Molesworth <cpan@perlsite.co.uk>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Fatal: '0.010'
  Test::HexString: '0'
  Test::More: '0.98'
  Test::Refcount: '0.07'
  perl: '5.010001'
configure_requires:
  ExtUtils::MakeMaker: '6.48'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Async-SOCKS
requires:
  Carp: '0'
  Future: '0.29'
  IO::Async: '0.62'
  Protocol::SOCKS: '0.003'
  parent: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-Async-SOCKS
  homepage: http://search.cpan.org/dist/Net-Async-SOCKS/
version: '0.002'
